analytics: {}
color:
  brandColors:
    - '#E8E8F0'
    - '#A87828'
    - '#000000'
    - '#F8C860'
    - '#F8C868'
  brandStrength: 0.693783
  lightness: 0.428091
  rhythmicContrast: 0.131991
  saturation: 0.596631
cta: {}
layout_spectrum: 0.011261
name: learning
opengraph: {}
purpose: []
typography_spectrum: 0.477477
