typography_spectrum: 0.477477
color:
  brandColors:
    - '#E8E8F0'
    - '#A87828'
    - '#000000'
    - '#F8C860'
    - '#F8C868'
  brandStrength: 0
  lightness: 0.428091
  saturation: 0.596631
  rhythmicContrast: 0.131991
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.011261
analytics:
  google: null
  facebook: null
  twitter: null
name: learning
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
